title: 'https://jinsburger.github.io/'
description: "Jinheon Lee (a.k.a howdays)'s Blog"
baseurl: "/"
url: "https://howdays.blog/"

header_pages:
  - index.md
  - about.md
  - contact.md
style: light 

footer: Â© 2025 Jinheon Lee

# Build settings
markdown: kramdown
#theme: jekyll-theme-console
remote_theme: b2a3e8/jekyll-theme-console

analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-6NYR8JYNJ2"
    anonymize_ip         : # true, false (default)
